# Generated by Django 5.0.13 on 2026-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('comercial', 'Comercial'), ('financeiro', 'Financeiro'), ('compras', 'Compras'), ('estoque', 'Estoque'), ('crm', 'CRM')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=240)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['area'],
            },
        ),
    ]
