# Generated by Codex on 2026-07-31

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
        ("empresas", "0028_posicaoestoqueomie_and_more"),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AprovacaoPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("reagendado", "Reagendado"),
                            ("erro_omie", "Erro OMIE"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("data_previsao_original", models.DateField(blank=True, null=True)),
                ("data_previsao_aprovada", models.DateField(blank=True, null=True)),
                ("resposta_omie", models.JSONField(blank=True, default=dict)),
                ("erro_omie", models.TextField(blank=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprovacoes_pagamentos",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conta_pagar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aprovacao_pagamento",
                        to="empresas.contapagaromie",
                    ),
                ),
            ],
            options={
                "verbose_name": "aprovacao de pagamento",
                "verbose_name_plural": "aprovacoes de pagamentos",
                "ordering": ["-atualizado_em"],
                "indexes": [
                    models.Index(fields=["status"], name="aprov_pag_status_idx"),
                    models.Index(
                        fields=["data_previsao_aprovada"],
                        name="aprov_pag_prev_idx",
                    ),
                ],
            },
        ),
    ]
