# Generated by Django 5.0.13 on 2026-06-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clientes/')),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('viewer', 'Visualizador')], default='viewer', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acesso à empresa',
                'verbose_name_plural': 'acessos às empresas',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', through='empresas.EmpresaUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='empresausuario',
            constraint=models.UniqueConstraint(fields=('empresa', 'usuario'), name='empresa_usuario_unico'),
        ),
    ]
