# Generated by Django 5.0.13 on 2026-07-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_categoriaomie_conta_dre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContaCorrenteOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descricao', models.CharField(max_length=40)),
                ('grupo', models.CharField(blank=True, max_length=2)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_conta_corrente_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'tipo de conta corrente OMIE',
                'verbose_name_plural': 'tipos de conta corrente OMIE',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContaCorrenteOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_omie', models.BigIntegerField()),
                ('codigo_integracao', models.CharField(blank=True, max_length=20)),
                ('tipo_codigo', models.CharField(blank=True, max_length=2)),
                ('codigo_banco', models.CharField(blank=True, max_length=3)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('codigo_agencia', models.CharField(blank=True, max_length=10)),
                ('numero_conta_corrente', models.CharField(blank=True, max_length=25)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_data', models.CharField(blank=True, max_length=10)),
                ('valor_limite', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nao_fluxo', models.BooleanField(default=False)),
                ('nao_resumo', models.BooleanField(default=False)),
                ('realiza_cobranca', models.BooleanField(default=False)),
                ('emite_boleto', models.BooleanField(default=False)),
                ('emite_pix', models.BooleanField(default=False)),
                ('importado_api', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
                ('inativo', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_correntes_omie', to='empresas.empresa')),
                ('tipo_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_correntes', to='empresas.tipocontacorrenteomie')),
            ],
            options={
                'verbose_name': 'conta corrente OMIE',
                'verbose_name_plural': 'contas correntes OMIE',
                'ordering': ['descricao', 'codigo_omie'],
            },
        ),
        migrations.AddConstraint(
            model_name='tipocontacorrenteomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='tipo_cc_omie_empresa_codigo_unico'),
        ),
        migrations.AddIndex(
            model_name='contacorrenteomie',
            index=models.Index(fields=['empresa', 'inativo'], name='conta_cc_emp_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='contacorrenteomie',
            index=models.Index(fields=['empresa', 'tipo_codigo'], name='conta_cc_emp_tipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacorrenteomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_omie'), name='conta_cc_omie_empresa_codigo_unico'),
        ),
    ]
