# Generated by Django 5.0.13 on 2026-07-05 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_tipocontacorrenteomie_contacorrenteomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagarOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lancamento_omie', models.BigIntegerField()),
                ('codigo_lancamento_integracao', models.CharField(blank=True, max_length=60)),
                ('codigo_cliente_fornecedor', models.BigIntegerField(blank=True, null=True)),
                ('id_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_projeto', models.BigIntegerField(blank=True, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_documento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status_titulo', models.CharField(blank=True, max_length=30)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('numero_documento_fiscal', models.CharField(blank=True, max_length=20)),
                ('numero_parcela', models.CharField(blank=True, max_length=7)),
                ('codigo_tipo_documento', models.CharField(blank=True, max_length=5)),
                ('id_origem', models.CharField(blank=True, max_length=4)),
                ('retem_cofins', models.BooleanField(default=False)),
                ('retem_csll', models.BooleanField(default=False)),
                ('retem_inss', models.BooleanField(default=False)),
                ('retem_ir', models.BooleanField(default=False)),
                ('retem_iss', models.BooleanField(default=False)),
                ('retem_pis', models.BooleanField(default=False)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('distribuicao', models.JSONField(blank=True, default=list)),
                ('cnab_integracao_bancaria', models.JSONField(blank=True, default=dict)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='empresas.categoriaomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='empresas.contacorrenteomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar_omie', to='empresas.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='empresas.cadastroomie')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='empresas.projetoomie')),
            ],
            options={
                'verbose_name': 'conta a pagar OMIE',
                'verbose_name_plural': 'contas a pagar OMIE',
                'ordering': ['data_vencimento', 'codigo_lancamento_omie'],
                'indexes': [models.Index(fields=['empresa', 'data_vencimento'], name='conta_pagar_emp_venc_idx'), models.Index(fields=['empresa', 'status_titulo'], name='conta_pagar_emp_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contapagaromie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_lancamento_omie'), name='conta_pagar_empresa_lancamento_unico'),
        ),
    ]
