# Generated by Django 5.0.13 on 2026-07-05 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_contareceberomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoContaCorrenteOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lancamento_omie', models.BigIntegerField()),
                ('codigo_lancamento_integracao', models.CharField(blank=True, max_length=20)),
                ('codigo_agrupamento', models.BigIntegerField(blank=True, null=True)),
                ('codigo_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('valor_lancamento', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('tipo_documento', models.CharField(blank=True, max_length=5)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('codigo_cliente_fornecedor', models.BigIntegerField(blank=True, null=True)),
                ('codigo_projeto', models.BigIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('natureza', models.CharField(blank=True, max_length=1)),
                ('origem', models.CharField(blank=True, max_length=4)),
                ('data_conciliacao', models.DateField(blank=True, null=True)),
                ('hora_conciliacao', models.CharField(blank=True, max_length=8)),
                ('usuario_conciliacao', models.CharField(blank=True, max_length=10)),
                ('identificacao_lancamento', models.CharField(blank=True, max_length=40)),
                ('codigo_lancamento_conta_pagar', models.BigIntegerField(blank=True, null=True)),
                ('codigo_lancamento_conta_receber', models.BigIntegerField(blank=True, null=True)),
                ('codigo_conta_corrente_destino', models.BigIntegerField(blank=True, null=True)),
                ('importado_api', models.BooleanField(default=False)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('departamentos', models.JSONField(blank=True, default=list)),
                ('cabecalho', models.JSONField(blank=True, default=dict)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('diversos', models.JSONField(blank=True, default=dict)),
                ('transferencia', models.JSONField(blank=True, default=dict)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conta_corrente', to='empresas.categoriaomie')),
                ('cliente_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conta_corrente', to='empresas.cadastroomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='empresas.contacorrenteomie')),
                ('conta_corrente_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='empresas.contacorrenteomie')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conta_corrente', to='empresas.contapagaromie')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conta_corrente', to='empresas.contareceberomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_conta_corrente_omie', to='empresas.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conta_corrente', to='empresas.projetoomie')),
            ],
            options={
                'verbose_name': 'lançamento de conta corrente OMIE',
                'verbose_name_plural': 'lançamentos de conta corrente OMIE',
                'ordering': ['data_lancamento', 'codigo_lancamento_omie'],
                'indexes': [models.Index(fields=['empresa', 'data_lancamento'], name='lanc_cc_emp_data_idx'), models.Index(fields=['empresa', 'natureza'], name='lanc_cc_emp_natureza_idx'), models.Index(fields=['empresa', 'codigo_conta_corrente'], name='lanc_cc_emp_conta_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lancamentocontacorrenteomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_lancamento_omie'), name='lanc_cc_empresa_codigo_unico'),
        ),
    ]
