# Generated by Django 5.0.13 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0012_lancamentocontacorrenteomie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoOmie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_produto", models.BigIntegerField()),
                ("codigo", models.CharField(blank=True, max_length=60)),
                (
                    "codigo_produto_integracao",
                    models.CharField(blank=True, max_length=100),
                ),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("descr_detalhada", models.TextField(blank=True)),
                ("unidade", models.CharField(blank=True, max_length=10)),
                ("ncm", models.CharField(blank=True, max_length=20)),
                ("ean", models.CharField(blank=True, max_length=30)),
                ("marca", models.CharField(blank=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                ("tipo_item", models.CharField(blank=True, max_length=5)),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "quantidade_estoque",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "peso_bruto",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "peso_liq",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "altura",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "largura",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                (
                    "profundidade",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=18,
                    ),
                ),
                ("codigo_familia", models.BigIntegerField(blank=True, null=True)),
                (
                    "codigo_integracao_familia",
                    models.CharField(blank=True, max_length=100),
                ),
                ("descricao_familia", models.CharField(blank=True, max_length=120)),
                ("bloqueado", models.BooleanField(default=False)),
                ("inativo", models.BooleanField(default=False)),
                ("importado_api", models.BooleanField(default=False)),
                ("produto_lote", models.BooleanField(default=False)),
                ("produto_variacao", models.BooleanField(default=False)),
                ("bloquear_exclusao", models.BooleanField(default=False)),
                ("info", models.JSONField(blank=True, default=dict)),
                ("recomendacoes_fiscais", models.JSONField(blank=True, default=dict)),
                ("dados_originais", models.JSONField(blank=True, default=dict)),
                ("sincronizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos_omie",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto OMIE",
                "verbose_name_plural": "produtos OMIE",
                "ordering": ["descricao", "codigo"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "inativo"],
                        name="prod_omie_emp_ativo_idx",
                    ),
                    models.Index(
                        fields=["empresa", "codigo"],
                        name="prod_omie_emp_codigo_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="produtoomie",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo_produto"),
                name="produto_omie_empresa_codigo_unico",
            ),
        ),
    ]
