# Generated by Django 5.0.13 on 2026-07-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_pedidoomie_pedidoitemomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servico', models.BigIntegerField()),
                ('codigo_integracao_servico', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('descricao_completa', models.TextField(blank=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_lc116', models.CharField(blank=True, max_length=20)),
                ('codigo_servico_municipal', models.CharField(blank=True, max_length=40)),
                ('id_tributacao', models.CharField(blank=True, max_length=10)),
                ('tipo_desconto', models.CharField(blank=True, max_length=10)),
                ('preco_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('aliquota_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('valor_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('aliquota_iss', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('ret_cofins', models.BooleanField(default=False)),
                ('ret_csll', models.BooleanField(default=False)),
                ('ret_inss', models.BooleanField(default=False)),
                ('ret_ir', models.BooleanField(default=False)),
                ('ret_iss', models.BooleanField(default=False)),
                ('ret_pis', models.BooleanField(default=False)),
                ('deduz_iss', models.BooleanField(default=False)),
                ('importado_api', models.BooleanField(default=False)),
                ('inativo', models.BooleanField(default=False)),
                ('cabecalho', models.JSONField(blank=True, default=dict)),
                ('descricao_dados', models.JSONField(blank=True, default=dict)),
                ('impostos', models.JSONField(blank=True, default=dict)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('int_listar', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_omie', to='empresas.categoriaomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'servico OMIE',
                'verbose_name_plural': 'servicos OMIE',
                'ordering': ['descricao', 'codigo'],
                'indexes': [models.Index(fields=['empresa', 'inativo'], name='serv_omie_emp_ativo_idx'), models.Index(fields=['empresa', 'codigo'], name='serv_omie_emp_codigo_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicoomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_servico'), name='servico_omie_empresa_codigo_unico'),
        ),
    ]
