# Generated by Django 5.0.13 on 2026-07-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_servicoomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServicoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_os', models.BigIntegerField()),
                ('codigo_integracao_os', models.CharField(blank=True, max_length=100)),
                ('numero_os', models.CharField(blank=True, max_length=30)),
                ('etapa', models.CharField(blank=True, max_length=10)),
                ('codigo_parcela', models.CharField(blank=True, max_length=20)),
                ('codigo_cliente', models.BigIntegerField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('quantidade_parcelas', models.PositiveIntegerField(default=0)),
                ('valor_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total_impostos_retidos', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('cidade_prestacao', models.CharField(blank=True, max_length=120)),
                ('numero_contrato', models.CharField(blank=True, max_length=60)),
                ('numero_recibo', models.CharField(blank=True, max_length=40)),
                ('uso_consumo', models.BooleanField(default=False)),
                ('cancelada', models.BooleanField(default=False)),
                ('faturada', models.BooleanField(default=False)),
                ('origem', models.CharField(blank=True, max_length=10)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('data_alteracao', models.DateField(blank=True, null=True)),
                ('data_faturamento', models.DateField(blank=True, null=True)),
                ('cabecalho', models.JSONField(blank=True, default=dict)),
                ('departamentos', models.JSONField(blank=True, default=list)),
                ('email', models.JSONField(blank=True, default=dict)),
                ('info_cadastro', models.JSONField(blank=True, default=dict)),
                ('informacoes_adicionais', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.JSONField(blank=True, default=dict)),
                ('parcelas', models.JSONField(blank=True, default=list)),
                ('servicos_prestados', models.JSONField(blank=True, default=list)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_omie', to='empresas.categoriaomie')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_omie', to='empresas.cadastroomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico_omie', to='empresas.contacorrenteomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'ordem de servico OMIE',
                'verbose_name_plural': 'ordens de servico OMIE',
                'ordering': ['-data_previsao', '-codigo_os'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServicoItemOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.BigIntegerField()),
                ('sequencia', models.PositiveIntegerField(default=0)),
                ('codigo_servico', models.BigIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_lc116', models.CharField(blank=True, max_length=20)),
                ('codigo_servico_municipal', models.CharField(blank=True, max_length=40)),
                ('tributacao_servico', models.CharField(blank=True, max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('aliquota_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('valor_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_acrescimos', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_outras_retencoes', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('aliquota_iss', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('valor_iss', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('base_iss', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('nao_gerar_financeiro', models.BooleanField(default=False)),
                ('reembolso', models.BooleanField(default=False)),
                ('retem_iss', models.BooleanField(default=False)),
                ('deduz_iss', models.BooleanField(default=False)),
                ('impostos', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ordem_servico_omie', to='empresas.categoriaomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ordem_servico_omie', to='empresas.empresa')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_ordem_servico_omie', to='empresas.servicoomie')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresas.ordemservicoomie')),
            ],
            options={
                'verbose_name': 'item de ordem de servico OMIE',
                'verbose_name_plural': 'itens de ordem de servico OMIE',
                'ordering': ['ordem_servico_id', 'sequencia', 'codigo_item'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemservicoomie',
            index=models.Index(fields=['empresa', 'data_previsao'], name='os_omie_emp_prev_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicoomie',
            index=models.Index(fields=['empresa', 'numero_os'], name='os_omie_emp_num_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicoomie',
            index=models.Index(fields=['empresa', 'faturada'], name='os_omie_emp_fat_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicoomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_os'), name='os_omie_empresa_codigo_unico'),
        ),
        migrations.AddIndex(
            model_name='ordemservicoitemomie',
            index=models.Index(fields=['empresa', 'codigo_servico'], name='os_item_emp_serv_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservicoitemomie',
            index=models.Index(fields=['empresa', 'codigo_categoria'], name='os_item_emp_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordemservicoitemomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_item'), name='os_item_omie_empresa_codigo_unico'),
        ),
    ]
