# Generated by Django 5.0.13 on 2026-07-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_ordemservicoomie_ordemservicoitemomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.BigIntegerField()),
                ('codigo_integracao_contrato', models.CharField(blank=True, max_length=100)),
                ('numero_contrato', models.CharField(blank=True, max_length=60)),
                ('codigo_situacao', models.CharField(blank=True, max_length=10)),
                ('tipo_faturamento', models.CharField(blank=True, max_length=10)),
                ('codigo_cliente', models.BigIntegerField(blank=True, null=True)),
                ('vigencia_inicial', models.DateField(blank=True, null=True)),
                ('vigencia_final', models.DateField(blank=True, null=True)),
                ('dia_faturamento', models.PositiveIntegerField(default=0)),
                ('valor_total_mes', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_categoria_reembolso', models.CharField(blank=True, max_length=20)),
                ('codigo_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('codigo_projeto', models.BigIntegerField(blank=True, null=True)),
                ('codigo_vendedor', models.BigIntegerField(blank=True, null=True)),
                ('cidade_prestacao', models.CharField(blank=True, max_length=120)),
                ('uso_consumo', models.BooleanField(default=False)),
                ('cabecalho', models.JSONField(blank=True, default=dict)),
                ('departamentos', models.JSONField(blank=True, default=list)),
                ('despesas_reembolsaveis', models.JSONField(blank=True, default=dict)),
                ('email_cliente', models.JSONField(blank=True, default=dict)),
                ('informacoes_adicionais', models.JSONField(blank=True, default=dict)),
                ('observacoes', models.JSONField(blank=True, default=dict)),
                ('venc_textos', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_omie', to='empresas.categoriaomie')),
                ('categoria_reembolso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_reembolso_omie', to='empresas.categoriaomie')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_omie', to='empresas.cadastroomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_omie', to='empresas.contacorrenteomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_omie', to='empresas.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_omie', to='empresas.projetoomie')),
            ],
            options={
                'verbose_name': 'contrato OMIE',
                'verbose_name_plural': 'contratos OMIE',
                'ordering': ['numero_contrato', 'codigo_contrato'],
            },
        ),
        migrations.CreateModel(
            name='ContratoItemOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.BigIntegerField()),
                ('sequencia', models.PositiveIntegerField(default=0)),
                ('codigo_servico', models.BigIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_lc116', models.CharField(blank=True, max_length=20)),
                ('codigo_servico_municipal', models.CharField(blank=True, max_length=40)),
                ('codigo_nbs', models.CharField(blank=True, max_length=40)),
                ('natureza_operacao', models.CharField(blank=True, max_length=10)),
                ('nao_gerar_financeiro', models.BooleanField(default=False)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_acrescimo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_deducao', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_outras_retencoes', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('aliquota_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('aliquota_iss', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('valor_iss', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('ret_iss', models.BooleanField(default=False)),
                ('deduz_iss', models.BooleanField(default=False)),
                ('item_cabecalho', models.JSONField(blank=True, default=dict)),
                ('item_descricao_servico', models.JSONField(blank=True, default=dict)),
                ('item_impostos', models.JSONField(blank=True, default=dict)),
                ('item_lei_transparencia', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_contrato_omie', to='empresas.categoriaomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_contrato_omie', to='empresas.empresa')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_contrato_omie', to='empresas.servicoomie')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresas.contratoomie')),
            ],
            options={
                'verbose_name': 'item de contrato OMIE',
                'verbose_name_plural': 'itens de contrato OMIE',
                'ordering': ['contrato_id', 'sequencia', 'codigo_item'],
            },
        ),
        migrations.AddIndex(
            model_name='contratoomie',
            index=models.Index(fields=['empresa', 'numero_contrato'], name='ctr_omie_emp_num_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoomie',
            index=models.Index(fields=['empresa', 'codigo_situacao'], name='ctr_omie_emp_sit_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratoomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_contrato'), name='contrato_omie_empresa_codigo_unico'),
        ),
        migrations.AddIndex(
            model_name='contratoitemomie',
            index=models.Index(fields=['empresa', 'codigo_servico'], name='ctr_item_emp_serv_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoitemomie',
            index=models.Index(fields=['empresa', 'codigo_categoria'], name='ctr_item_emp_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratoitemomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_item'), name='contrato_item_omie_empresa_codigo_unico'),
        ),
    ]
