# Generated by Django 5.0.13 on 2026-07-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_contratoomie_contratoitemomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('codigo_integracao', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comissao', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('fatura_pedido', models.BooleanField(default=False)),
                ('visualiza_pedido', models.BooleanField(default=False)),
                ('inativo', models.BooleanField(default=False)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'vendedor OMIE',
                'verbose_name_plural': 'vendedores OMIE',
                'ordering': ['nome', 'codigo'],
                'indexes': [models.Index(fields=['empresa', 'inativo'], name='vend_omie_emp_ativo_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendedoromie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='vendedor_omie_empresa_codigo_unico'),
        ),
    ]
