# Generated by Django 5.0.13 on 2026-07-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_vendedoromie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVendedorComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_vendedores_comerciais', to='empresas.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_comerciais', to='empresas.vendedoromie')),
            ],
            options={
                'verbose_name': 'meta comercial por vendedor',
                'verbose_name_plural': 'metas comerciais por vendedor',
                'ordering': ['vendedor__nome', 'vendedor__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='metavendedorcomercial',
            constraint=models.UniqueConstraint(fields=('empresa', 'vendedor'), name='meta_vendedor_empresa_vendedor_unico'),
        ),
    ]
