# Generated by Django 5.0.13 on 2026-07-14 01:26

from django.db import migrations, models


def preencher_codigo_vendedor(apps, schema_editor):
    ordem_servico_model = apps.get_model("empresas", "OrdemServicoOmie")
    atualizadas = []
    for ordem in ordem_servico_model.objects.all().only("pk", "dados_originais"):
        cabecalho = (ordem.dados_originais or {}).get("Cabecalho") or {}
        codigo = cabecalho.get("nCodVend")
        try:
            codigo = int(codigo) if codigo not in (None, "", 0, "0") else None
        except (TypeError, ValueError):
            codigo = None
        if codigo:
            ordem.codigo_vendedor = codigo
            atualizadas.append(ordem)
    if atualizadas:
        ordem_servico_model.objects.bulk_update(atualizadas, ["codigo_vendedor"])


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_metavendedorcomercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoomie',
            name='codigo_vendedor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(preencher_codigo_vendedor, migrations.RunPython.noop),
    ]
