# Generated by Django 5.0.13 on 2026-07-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_ordemservicoomie_codigo_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresausuario',
            name='areas_permitidas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='dashboards_permitidos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
