# Generated by Django 5.0.13 on 2026-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresausuario_areas_permitidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacorrenteomie',
            name='saldo_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='contacorrenteomie',
            name='saldo_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
