# Generated by Django 5.0.13 on 2026-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_contacorrenteomie_saldo_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='resumo_financeiro_omie',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empresa',
            name='saldo_contas_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='saldo_contas_omie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
