# Generated by Django 5.0.13 on 2026-07-22 17:43

import apps.empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0023_empresa_resumo_financeiro_omie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metavendedorcomercial',
            options={'ordering': ['ano', 'mes', 'vendedor__nome', 'vendedor__codigo'], 'verbose_name': 'meta comercial por vendedor', 'verbose_name_plural': 'metas comerciais por vendedor'},
        ),
        migrations.RemoveConstraint(
            model_name='metavendedorcomercial',
            name='meta_vendedor_empresa_vendedor_unico',
        ),
        migrations.AddField(
            model_name='metavendedorcomercial',
            name='ano',
            field=models.PositiveSmallIntegerField(default=apps.empresas.models.ano_atual),
        ),
        migrations.AddField(
            model_name='metavendedorcomercial',
            name='mes',
            field=models.PositiveSmallIntegerField(default=apps.empresas.models.mes_atual),
        ),
        migrations.AddConstraint(
            model_name='metavendedorcomercial',
            constraint=models.UniqueConstraint(fields=('empresa', 'vendedor', 'ano', 'mes'), name='meta_vendedor_empresa_vendedor_periodo_unico'),
        ),
    ]
