# Generated by Django 5.0.13 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0024_alter_metavendedorcomercial_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="grupo",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
