# Generated by Django 5.0.13 on 2026-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0025_empresa_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaomie',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriaomie',
            name='natureza',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contapagaromie',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='contareceberomie',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='lancamentocontacorrenteomie',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
