# Generated by Django 5.0.13 on 2026-07-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_alter_categoriaomie_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoFinanceiroOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_titulo', models.BigIntegerField()),
                ('codigo_titulo_repeticao', models.BigIntegerField(blank=True, null=True)),
                ('codigo_cliente_fornecedor', models.BigIntegerField(blank=True, null=True)),
                ('codigo_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=20)),
                ('codigo_projeto', models.BigIntegerField(blank=True, null=True)),
                ('grupo', models.CharField(blank=True, max_length=30)),
                ('natureza', models.CharField(blank=True, max_length=1)),
                ('origem', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('liquidado', models.BooleanField(default=False)),
                ('tipo_documento', models.CharField(blank=True, max_length=5)),
                ('numero_titulo', models.CharField(blank=True, max_length=60)),
                ('numero_boleto', models.CharField(blank=True, max_length=60)),
                ('numero_parcela', models.CharField(blank=True, max_length=10)),
                ('cpf_cnpj_cliente', models.CharField(blank=True, max_length=20)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_titulo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_aberto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='empresas.categoriaomie')),
                ('cliente_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='empresas.cadastroomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='empresas.contacorrenteomie')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='empresas.contapagaromie')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='empresas.contareceberomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_financeiros_omie', to='empresas.empresa')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='empresas.projetoomie')),
            ],
            options={
                'verbose_name': 'movimento financeiro OMIE',
                'verbose_name_plural': 'movimentos financeiros OMIE',
                'ordering': ['data_vencimento', 'codigo_titulo'],
                'indexes': [models.Index(fields=['empresa', 'data_vencimento'], name='mov_fin_emp_venc_idx'), models.Index(fields=['empresa', 'grupo', 'natureza'], name='mov_fin_emp_grupo_nat_idx'), models.Index(fields=['empresa', 'liquidado'], name='mov_fin_emp_liq_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='movimentofinanceiroomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_titulo'), name='mov_fin_empresa_titulo_unico'),
        ),
    ]
