# Generated by Django 5.0.13 on 2026-07-29 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0027_movimentofinanceiroomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoEstoqueOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.BigIntegerField()),
                ('codigo_local_estoque', models.BigIntegerField(default=0)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('codigo_integracao', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_posicao', models.DateField(blank=True, null=True)),
                ('estoque_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fisico', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('pendente', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('reservado', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cmc', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('preco_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_estoque_omie', to='empresas.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posicoes_estoque_omie', to='empresas.produtoomie')),
            ],
            options={
                'verbose_name': 'posicao de estoque OMIE',
                'verbose_name_plural': 'posicoes de estoque OMIE',
                'ordering': ['descricao', 'codigo'],
                'indexes': [models.Index(fields=['empresa', 'codigo_produto'], name='pos_est_emp_prod_idx'), models.Index(fields=['empresa', 'codigo_local_estoque'], name='pos_est_emp_local_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='posicaoestoqueomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_produto', 'codigo_local_estoque'), name='pos_est_emp_prod_local_unico'),
        ),
    ]
