# Generated by Django 5.0.13 on 2026-08-01 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_posicaoestoqueomie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sincronizacaoomie',
            name='agendada_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sincronizacaoomie',
            name='disparada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes_omie_disparadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sincronizacaoomie',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('agendada', 'Agendada')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='AgendamentoSincronizacaoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('tipo_agendamento', models.CharField(choices=[('dias_semana', 'Dia da semana'), ('todo_dia', 'Todo dia')], default='todo_dia', max_length=20)),
                ('dias_semana', models.JSONField(blank=True, default=list)),
                ('dia_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horarios', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_sincronizacao_omie_atualizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_sincronizacao_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'agendamento de sincronizacao OMIE',
                'verbose_name_plural': 'agendamentos de sincronizacao OMIE',
                'ordering': ['empresa__nome_fantasia'],
            },
        ),
        migrations.AddField(
            model_name='sincronizacaoomie',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='empresas.agendamentosincronizacaoomie'),
        ),
        migrations.AddConstraint(
            model_name='sincronizacaoomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'agendamento', 'agendada_para'), name='sync_omie_agendamento_horario_unico'),
        ),
    ]
