# Generated by Django 5.0.13 on 2026-08-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0029_sincronizacaoomie_agendada_para_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagaromie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contapagaromie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contapagaromie',
            index=models.Index(fields=['empresa', 'ativo_omie'], name='conta_pagar_emp_ativo_idx'),
        ),
    ]
