# Generated by Django 5.0.13 on 2026-08-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0031_aumenta_codigos_categoria_omie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompraOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.BigIntegerField()),
                ('codigo_pedido_integracao', models.CharField(blank=True, max_length=100)),
                ('numero_pedido', models.CharField(blank=True, max_length=30)),
                ('numero_pedido_fornecedor', models.CharField(blank=True, max_length=30)),
                ('etapa', models.CharField(blank=True, max_length=10)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('observacao', models.TextField(blank=True)),
                ('observacao_interna', models.TextField(blank=True)),
                ('codigo_fornecedor', models.BigIntegerField(blank=True, null=True)),
                ('codigo_comprador', models.BigIntegerField(blank=True, null=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=50)),
                ('codigo_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('codigo_projeto', models.BigIntegerField(blank=True, null=True)),
                ('codigo_parcela', models.CharField(blank=True, max_length=20)),
                ('quantidade_parcelas', models.PositiveIntegerField(default=0)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('hora_inclusao', models.CharField(blank=True, max_length=10)),
                ('valor_mercadorias', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total_pedido', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_frete', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_seguro', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_outras_despesas', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cabecalho_consulta', models.JSONField(blank=True, default=dict)),
                ('caracteristicas_consulta', models.JSONField(blank=True, default=list)),
                ('departamentos_consulta', models.JSONField(blank=True, default=list)),
                ('frete_consulta', models.JSONField(blank=True, default=dict)),
                ('parcelas_consulta', models.JSONField(blank=True, default=list)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_omie', to='empresas.categoriaomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_omie', to='empresas.contacorrenteomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_compra_omie', to='empresas.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_omie', to='empresas.cadastroomie')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_omie', to='empresas.projetoomie')),
            ],
            options={
                'verbose_name': 'pedido de compra OMIE',
                'verbose_name_plural': 'pedidos de compra OMIE',
                'ordering': ['-data_previsao', '-codigo_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraItemOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.BigIntegerField()),
                ('codigo_item_integracao', models.CharField(blank=True, max_length=100)),
                ('codigo_produto', models.BigIntegerField(blank=True, null=True)),
                ('codigo_produto_texto', models.CharField(blank=True, max_length=60)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=10)),
                ('ncm', models.CharField(blank=True, max_length=20)),
                ('ean', models.CharField(blank=True, max_length=30)),
                ('codigo_categoria', models.CharField(blank=True, max_length=50)),
                ('codigo_local_estoque', models.BigIntegerField(blank=True, null=True)),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('quantidade_recebida', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_mercadoria', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_desconto', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_frete', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_despesas', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_seguro', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_icms', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_ipi', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_pis', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_cofins', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('valor_st', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('peso_bruto', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('peso_liquido', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('observacao', models.TextField(blank=True)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_compra_omie', to='empresas.categoriaomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido_compra_omie', to='empresas.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_compra_omie', to='empresas.produtoomie')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresas.pedidocompraomie')),
            ],
            options={
                'verbose_name': 'item de pedido de compra OMIE',
                'verbose_name_plural': 'itens de pedido de compra OMIE',
                'ordering': ['pedido_id', 'codigo_item'],
            },
        ),
        migrations.AddIndex(
            model_name='pedidocompraomie',
            index=models.Index(fields=['empresa', 'data_previsao'], name='ped_comp_emp_prev_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompraomie',
            index=models.Index(fields=['empresa', 'numero_pedido'], name='ped_comp_emp_num_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompraomie',
            index=models.Index(fields=['empresa', 'codigo_fornecedor'], name='ped_comp_emp_forn_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompraomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_pedido'), name='ped_compra_omie_empresa_codigo_unico'),
        ),
        migrations.AddIndex(
            model_name='pedidocompraitemomie',
            index=models.Index(fields=['empresa', 'codigo_produto'], name='ped_comp_item_emp_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidocompraitemomie',
            index=models.Index(fields=['empresa', 'codigo_categoria'], name='ped_comp_item_emp_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedidocompraitemomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_item'), name='ped_comp_item_omie_empresa_codigo_unico'),
        ),
    ]
