# Generated by Django 5.0.13 on 2026-08-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0032_pedidocompraomie_pedidocompraitemomie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaomie',
            name='categoria_superior',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='categoriaomie',
            name='codigo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contapagaromie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contareceberomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contratoitemomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contratoomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='contratoomie',
            name='codigo_categoria_reembolso',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='lancamentocontacorrenteomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiroomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ordemservicoitemomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ordemservicoomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pedidocompraitemomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pedidocompraomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pedidoitemomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pedidoomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='servicoomie',
            name='codigo_categoria',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
