# Generated by Django 5.0.13 on 2026-08-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_alter_categoriaomie_categoria_superior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaomie',
            name='descricao_padrao',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
