# Generated by Django 5.0.13 on 2026-08-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0034_alter_categoriaomie_descricao_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cadastroomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriaomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriaomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacorrenteomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacorrenteomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contareceberomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contareceberomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamentoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departamentoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentocontacorrenteomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lancamentocontacorrenteomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimentofinanceiroomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservicoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordemservicoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompraomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidocompraomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posicaoestoqueomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posicaoestoqueomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produtoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projetoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicoomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicoomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipocontacorrenteomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipocontacorrenteomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendedoromie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendedoromie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
