# Generated by Django 5.0.13 on 2026-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0035_cadastroomie_ativo_omie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoitemomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratoitemomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservicoitemomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordemservicoitemomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocompraitemomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidocompraitemomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitemomie',
            name='ativo_omie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedidoitemomie',
            name='ultima_presenca_omie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
