# Generated by Codex on 2026-08-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0036_contratoitemomie_ativo_omie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecebimentoNfeOmie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_recebimento", models.BigIntegerField()),
                ("chave_nfe", models.CharField(blank=True, max_length=60)),
                ("etapa", models.CharField(blank=True, max_length=10)),
                ("modelo_nfe", models.CharField(blank=True, max_length=10)),
                ("numero_nfe", models.CharField(blank=True, max_length=30)),
                ("serie_nfe", models.CharField(blank=True, max_length=10)),
                ("data_emissao_nfe", models.DateField(blank=True, null=True)),
                ("data_registro", models.DateField(blank=True, null=True)),
                ("codigo_fornecedor", models.BigIntegerField(blank=True, null=True)),
                ("valor_nfe", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("categoria_compra", models.CharField(blank=True, max_length=80)),
                ("codigo_conta", models.BigIntegerField(blank=True, null=True)),
                ("cabec", models.JSONField(blank=True, default=dict)),
                ("info_adicionais", models.JSONField(blank=True, default=dict)),
                ("parcelas", models.JSONField(blank=True, default=dict)),
                ("totais", models.JSONField(blank=True, default=dict)),
                ("transporte", models.JSONField(blank=True, default=dict)),
                ("dados_originais", models.JSONField(blank=True, default=dict)),
                ("ativo_omie", models.BooleanField(default=True)),
                ("ultima_presenca_omie", models.DateTimeField(blank=True, null=True)),
                ("sincronizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recebimentos_nfe_omie", to="empresas.empresa")),
            ],
            options={
                "verbose_name": "recebimento de NF-e OMIE",
                "verbose_name_plural": "recebimentos de NF-e OMIE",
                "ordering": ["-data_registro", "-codigo_recebimento"],
            },
        ),
        migrations.CreateModel(
            name="RecebimentoNfeItemOmie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_recebimento", models.BigIntegerField()),
                ("sequencia", models.PositiveIntegerField(default=0)),
                ("numero_pedido_compra", models.CharField(blank=True, max_length=30)),
                ("data_recebimento", models.DateField(blank=True, null=True)),
                ("codigo_produto_texto", models.CharField(blank=True, max_length=60)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("quantidade_nfe", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("quantidade_recebida", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("preco_unitario", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("valor_total_item", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("item_cabec", models.JSONField(blank=True, default=dict)),
                ("item_ajustes", models.JSONField(blank=True, default=dict)),
                ("dados_originais", models.JSONField(blank=True, default=dict)),
                ("ativo_omie", models.BooleanField(default=True)),
                ("ultima_presenca_omie", models.DateTimeField(blank=True, null=True)),
                ("sincronizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens_recebimento_nfe_omie", to="empresas.empresa")),
                ("recebimento", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="empresas.recebimentonfeomie")),
            ],
            options={
                "verbose_name": "item de recebimento de NF-e OMIE",
                "verbose_name_plural": "itens de recebimento de NF-e OMIE",
                "ordering": ["recebimento_id", "sequencia"],
            },
        ),
        migrations.AddIndex(model_name="recebimentonfeomie", index=models.Index(fields=["empresa", "chave_nfe"], name="receb_nfe_emp_chave_idx")),
        migrations.AddIndex(model_name="recebimentonfeomie", index=models.Index(fields=["empresa", "data_registro"], name="receb_nfe_emp_data_idx")),
        migrations.AddConstraint(model_name="recebimentonfeomie", constraint=models.UniqueConstraint(fields=("empresa", "codigo_recebimento"), name="receb_nfe_omie_empresa_cod_unico")),
        migrations.AddIndex(model_name="recebimentonfeitemomie", index=models.Index(fields=["empresa", "numero_pedido_compra"], name="receb_item_emp_ped_idx")),
        migrations.AddIndex(model_name="recebimentonfeitemomie", index=models.Index(fields=["empresa", "codigo_produto_texto"], name="receb_item_emp_prod_idx")),
        migrations.AddIndex(model_name="recebimentonfeitemomie", index=models.Index(fields=["empresa", "data_recebimento"], name="receb_item_emp_data_idx")),
        migrations.AddConstraint(model_name="recebimentonfeitemomie", constraint=models.UniqueConstraint(fields=("empresa", "codigo_recebimento", "sequencia"), name="receb_nfe_item_empresa_seq_unico")),
    ]
