# Generated by Django 5.0.13 on 2026-08-22 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0037_recebimentonfeomie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesqTituloFinanceiroOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_titulo', models.BigIntegerField()),
                ('codigo_titulo_repeticao', models.BigIntegerField(blank=True, null=True)),
                ('codigo_cliente_fornecedor', models.BigIntegerField(blank=True, null=True)),
                ('codigo_conta_corrente', models.BigIntegerField(blank=True, null=True)),
                ('codigo_categoria', models.CharField(blank=True, max_length=80)),
                ('natureza', models.CharField(blank=True, max_length=1)),
                ('origem', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('liquidado', models.BooleanField(default=False)),
                ('tipo_documento', models.CharField(blank=True, max_length=5)),
                ('numero_titulo', models.CharField(blank=True, max_length=60)),
                ('numero_documento_fiscal', models.CharField(blank=True, max_length=60)),
                ('cpf_cnpj_cliente', models.CharField(blank=True, max_length=20)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('data_previsao', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_titulo', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_aberto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_csll', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_inss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_ir', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_iss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observacao', models.TextField(blank=True)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('departamentos', models.JSONField(blank=True, default=list)),
                ('lancamentos', models.JSONField(blank=True, default=list)),
                ('cabec_titulo', models.JSONField(blank=True, default=dict)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('ativo_omie', models.BooleanField(default=True)),
                ('ultima_presenca_omie', models.DateTimeField(blank=True, null=True)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesq_titulos_financeiros', to='empresas.categoriaomie')),
                ('cliente_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesq_titulos_financeiros', to='empresas.cadastroomie')),
                ('conta_corrente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesq_titulos_financeiros', to='empresas.contacorrenteomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesq_titulos_financeiros_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'titulo financeiro pesquisado OMIE',
                'verbose_name_plural': 'titulos financeiros pesquisados OMIE',
                'db_table': 'empresas_pesq_titulofinanceiroomie',
                'ordering': ['data_previsao', 'codigo_titulo'],
                'indexes': [models.Index(fields=['empresa', 'data_previsao'], name='pesq_tit_emp_prev_idx'), models.Index(fields=['empresa', 'natureza', 'status'], name='pesq_tit_emp_nat_st_idx'), models.Index(fields=['empresa', 'liquidado'], name='pesq_tit_emp_liq_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pesqtitulofinanceiroomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_titulo'), name='pesq_tit_fin_emp_titulo_unico'),
        ),
    ]
