# Generated by Django 5.0.13 on 2026-08-25 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0038_pesqtitulofinanceiroomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoPendenteEstoqueOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.BigIntegerField()),
                ('codigo_local_estoque', models.BigIntegerField(default=0)),
                ('quantidade_entrada', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('quantidade_saida', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('ativo_omie', models.BooleanField(default=True)),
                ('ultima_presenca_omie', models.DateTimeField(blank=True, null=True)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_pendentes_estoque_omie', to='empresas.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_pendentes_estoque_omie', to='empresas.produtoomie')),
            ],
            options={
                'verbose_name': 'saldo pendente de estoque OMIE',
                'verbose_name_plural': 'saldos pendentes de estoque OMIE',
                'ordering': ['codigo_produto', 'codigo_local_estoque'],
                'indexes': [models.Index(fields=['empresa', 'codigo_produto'], name='saldo_pend_est_emp_prod_idx'), models.Index(fields=['empresa', 'codigo_local_estoque'], name='saldo_pend_est_emp_local_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='saldopendenteestoqueomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_produto', 'codigo_local_estoque'), name='saldo_pend_est_emp_prod_local_unico'),
        ),
    ]
