# Generated by Django 5.0.13 on 2026-08-25 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0039_saldopendenteestoqueomie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoqueOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_local_estoque', models.BigIntegerField()),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('tipo', models.CharField(blank=True, max_length=1)),
                ('codigo_cliente', models.BigIntegerField(blank=True, null=True)),
                ('padrao', models.BooleanField(default=False)),
                ('inativo', models.BooleanField(default=False)),
                ('disponivel_ordem_producao', models.BooleanField(default=False)),
                ('disponivel_consumo_op', models.BooleanField(default=False)),
                ('disponivel_remessa', models.BooleanField(default=False)),
                ('disponivel_venda', models.BooleanField(default=False)),
                ('considera_sugestao_compra', models.BooleanField(default=False)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('hora_inclusao', models.CharField(blank=True, max_length=8)),
                ('usuario_inclusao', models.CharField(blank=True, max_length=20)),
                ('data_alteracao', models.DateField(blank=True, null=True)),
                ('hora_alteracao', models.CharField(blank=True, max_length=8)),
                ('usuario_alteracao', models.CharField(blank=True, max_length=20)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('ativo_omie', models.BooleanField(default=True)),
                ('ultima_presenca_omie', models.DateTimeField(blank=True, null=True)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais_estoque_omie', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'local de estoque OMIE',
                'verbose_name_plural': 'locais de estoque OMIE',
                'ordering': ['descricao', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='posicaoestoqueomie',
            name='local_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posicoes_estoque_omie', to='empresas.localestoqueomie'),
        ),
        migrations.AddField(
            model_name='saldopendenteestoqueomie',
            name='local_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_pendentes_estoque_omie', to='empresas.localestoqueomie'),
        ),
        migrations.AddIndex(
            model_name='localestoqueomie',
            index=models.Index(fields=['empresa', 'codigo'], name='local_est_omie_emp_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='localestoqueomie',
            index=models.Index(fields=['empresa', 'inativo'], name='local_est_omie_emp_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='localestoqueomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_local_estoque'), name='local_est_omie_empresa_codigo_unico'),
        ),
    ]
