# Generated by Django 5.0.13 on 2026-08-26 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0040_localestoqueomie_posicaoestoqueomie_local_estoque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoUsuarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('erro_login', 'Erro de login'), ('acesso_empresa', 'Acesso a empresa'), ('modulo', 'Modulo'), ('dashboard', 'Dashboard'), ('alteracao', 'Alteracao'), ('exclusao', 'Exclusao')], db_index=True, max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('caminho', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acoes', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de acao do usuario',
                'verbose_name_plural': 'logs de acoes dos usuarios',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'criado_em'], name='log_acao_emp_data_idx'), models.Index(fields=['usuario', 'criado_em'], name='log_acao_usr_data_idx'), models.Index(fields=['tipo', 'criado_em'], name='log_acao_tipo_data_idx')],
            },
        ),
    ]
