# Generated by Django 5.0.13 on 2026-09-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0041_acaousuariolog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfseOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_nf', models.BigIntegerField()),
                ('numero_nfse', models.CharField(blank=True, max_length=40)),
                ('serie_nfse', models.CharField(blank=True, max_length=20)),
                ('status_nfse', models.CharField(blank=True, max_length=1)),
                ('codigo_os', models.BigIntegerField(blank=True, null=True)),
                ('numero_os', models.CharField(blank=True, max_length=30)),
                ('codigo_cliente', models.BigIntegerField(blank=True, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_nfse', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('cabecalho', models.JSONField(blank=True, default=dict)),
                ('ordem_servico_dados', models.JSONField(blank=True, default=dict)),
                ('rps', models.JSONField(blank=True, default=dict)),
                ('adicionais', models.JSONField(blank=True, default=dict)),
                ('servicos', models.JSONField(blank=True, default=list)),
                ('valores', models.JSONField(blank=True, default=dict)),
                ('emissao', models.JSONField(blank=True, default=dict)),
                ('dados_originais', models.JSONField(blank=True, default=dict)),
                ('ativo_omie', models.BooleanField(default=True)),
                ('ultima_presenca_omie', models.DateTimeField(blank=True, null=True)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfses_omie', to='empresas.cadastroomie')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfses_omie', to='empresas.empresa')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfses', to='empresas.ordemservicoomie')),
            ],
            options={
                'verbose_name': 'NFS-e OMIE',
                'verbose_name_plural': 'NFS-es OMIE',
                'ordering': ['-data_emissao', '-codigo_nf'],
                'indexes': [models.Index(fields=['empresa', 'codigo_os'], name='nfse_omie_emp_os_idx'), models.Index(fields=['empresa', 'status_nfse'], name='nfse_omie_emp_status_idx'), models.Index(fields=['empresa', 'data_emissao'], name='nfse_omie_emp_emissao_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='nfseomie',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo_nf'), name='nfse_omie_empresa_codigo_unico'),
        ),
    ]
