# Generated by Codex on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0042_nfseomie_nfseomie_nfse_omie_empresa_codigo_unico"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentoEstoqueOmie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_produto", models.BigIntegerField()),
                ("codigo_local_estoque", models.BigIntegerField(default=0)),
                ("codigo", models.CharField(blank=True, max_length=60)),
                ("codigo_integracao", models.CharField(blank=True, max_length=100)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("codigo_origem", models.CharField(blank=True, max_length=10)),
                ("descricao_origem", models.CharField(blank=True, max_length=120)),
                ("operacao", models.CharField(blank=True, max_length=20)),
                ("data_movimento", models.DateField(blank=True, null=True)),
                ("cancelamento", models.BooleanField(default=False)),
                ("devolucao", models.BooleanField(default=False)),
                ("codigo_movimento", models.BigIntegerField()),
                ("codigo_documento", models.BigIntegerField(blank=True, null=True)),
                ("codigo_pedido", models.BigIntegerField(blank=True, null=True)),
                ("codigo_recebimento", models.BigIntegerField(blank=True, null=True)),
                ("codigo_ajuste", models.BigIntegerField(blank=True, null=True)),
                ("numero_documento", models.CharField(blank=True, max_length=60)),
                ("numero_pedido", models.CharField(blank=True, max_length=120)),
                ("quantidade_anterior", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("quantidade_entrada", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("quantidade_saida", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("quantidade_atual", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("cmc_unitario", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("cmc_total", models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ("movimentos_periodo", models.JSONField(blank=True, default=list)),
                ("dados_originais", models.JSONField(blank=True, default=dict)),
                ("ativo_omie", models.BooleanField(default=True)),
                ("ultima_presenca_omie", models.DateTimeField(blank=True, null=True)),
                ("sincronizado_em", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="movimentos_estoque_omie", to="empresas.empresa")),
                ("local_estoque", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movimentos_estoque_omie", to="empresas.localestoqueomie")),
                ("produto", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movimentos_estoque_omie", to="empresas.produtoomie")),
            ],
            options={
                "verbose_name": "movimento de estoque OMIE",
                "verbose_name_plural": "movimentos de estoque OMIE",
                "ordering": ["-data_movimento", "-codigo_movimento"],
                "indexes": [
                    models.Index(fields=["empresa", "codigo_produto", "data_movimento"], name="mov_est_emp_prod_data_idx"),
                    models.Index(fields=["empresa", "codigo_local_estoque"], name="mov_est_emp_local_idx"),
                    models.Index(fields=["empresa", "codigo_pedido"], name="mov_est_emp_pedido_idx"),
                    models.Index(fields=["empresa", "codigo_recebimento"], name="mov_est_emp_receb_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="movimentoestoqueomie",
            constraint=models.UniqueConstraint(fields=("empresa", "codigo_movimento"), name="mov_est_omie_empresa_mov_unico"),
        ),
    ]
