# Generated by Django 5.0.13 on 2026-10-06 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0047_sincronizacaoomie_celery_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sincronizacaoomie',
            name='parada_solicitada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sincronizacaoomie',
            name='parada_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes_omie_interrompidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sincronizacaoomie',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('interrompida', 'Interrompida pelo usuario'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
