# Generated by Django 5.0.13 on 2026-08-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0031_aumenta_codigos_categoria_omie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetConfiguracaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_controle', models.CharField(choices=[('produto', 'Produto'), ('familia_produto', 'Familia de produto'), ('projeto', 'Projeto'), ('fornecedor', 'Fornecedor')], default='produto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_compras', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'configuracao de budget de compras',
                'verbose_name_plural': 'configuracoes de budget de compras',
            },
        ),
        migrations.CreateModel(
            name='BudgetLimiteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_controle', models.CharField(choices=[('produto', 'Produto'), ('familia_produto', 'Familia de produto'), ('projeto', 'Projeto'), ('fornecedor', 'Fornecedor')], max_length=20)),
                ('referencia_codigo', models.CharField(max_length=120)),
                ('referencia_nome', models.CharField(blank=True, max_length=255)),
                ('estoque_minimo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('limite_compra', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites', to='compras.budgetconfiguracaocompra')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_budget_compras', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'limite de budget de compras',
                'verbose_name_plural': 'limites de budget de compras',
                'ordering': ['referencia_nome', 'referencia_codigo'],
                'indexes': [models.Index(fields=['empresa', 'tipo_controle'], name='budget_limite_emp_tipo_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetlimitecompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_controle', 'referencia_codigo'), name='budget_limite_empresa_tipo_ref_unico'),
        ),
    ]
