# Generated by Django 5.0.13 on 2026-08-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetconfiguracaocompra',
            name='tipos_controle',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
