# Generated by Django 5.0.13 on 2026-08-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_budgetconfiguracaocompra_tipos_controle'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetconfiguracaocompra',
            name='modalidades_controle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='budgetconfiguracaocompra',
            name='totais_grupo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
