# Generated by Django 5.0.13 on 2026-08-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_budgetconfiguracaocompra_modalidades_controle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetconfiguracaocompra',
            name='periodicidades_controle',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
