# Generated by Django 5.0.13 on 2026-08-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_budgetconfiguracaocompra_meses_controle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetconfiguracaocompra',
            name='tipo_controle',
            field=models.CharField(choices=[('produto', 'Produto'), ('familia_produto', 'Familia de produto'), ('projeto', 'Projeto'), ('fornecedor', 'Fornecedor'), ('departamento', 'Departamento')], default='produto', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetlimitecompra',
            name='tipo_controle',
            field=models.CharField(choices=[('produto', 'Produto'), ('familia_produto', 'Familia de produto'), ('projeto', 'Projeto'), ('fornecedor', 'Fornecedor'), ('departamento', 'Departamento')], max_length=20),
        ),
    ]
