# Generated by Django 5.0.13 on 2026-08-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_budgetconfiguracaocompra_tipo_controle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetconfiguracaocompra',
            name='tipo_controle',
            field=models.CharField(choices=[('produto', 'Produto'), ('familia_produto', 'Familia de produto'), ('projeto', 'Projeto'), ('fornecedor', 'Fornecedor'), ('departamento', 'Departamento'), ('categoria', 'Categoria')], default='produto', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetlimitecompra',
            name='tipo_controle',
            field=models.CharField(choices=[('produto', 'Produto'), ('familia_produto', 'Familia de produto'), ('projeto', 'Projeto'), ('fornecedor', 'Fornecedor'), ('departamento', 'Departamento'), ('categoria', 'Categoria')], max_length=20),
        ),
    ]
