# Generated by Django 5.0.13 on 2026-08-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_budgetconfiguracaocompra_tipo_controle_and_more'),
        ('empresas', '0036_contratoitemomie_ativo_omie_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budgetlimitecompra',
            name='budget_limite_empresa_tipo_ref_unico',
        ),
        migrations.RemoveIndex(
            model_name='budgetlimitecompra',
            name='budget_limite_emp_tipo_idx',
        ),
        migrations.AddField(
            model_name='budgetlimitecompra',
            name='mes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='budgetlimitecompra',
            index=models.Index(fields=['empresa', 'tipo_controle', 'mes'], name='budget_limite_emp_tipo_mes_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetlimitecompra',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_controle', 'referencia_codigo', 'mes'), name='budget_limite_empresa_tipo_ref_mes_unico'),
        ),
    ]
